// ABI copied from `deployments/sepolia/PhantomDB.json` (generated by hardhat-deploy).
export const PHANTOM_DB_ABI = [
  {
    type: 'event',
    name: 'PurchaseAdded',
    inputs: [
      { name: 'merchant', type: 'address', indexed: true },
      { name: 'index', type: 'uint256', indexed: true },
      { name: 'item', type: 'string', indexed: false },
      { name: 'timestamp', type: 'uint64', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'addPurchase',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'item', type: 'string' },
      { name: 'userIdExt', type: 'bytes32' },
      { name: 'quantityExt', type: 'bytes32' },
      { name: 'amountExt', type: 'bytes32' },
      { name: 'inputProof', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getPurchaseCount',
    stateMutability: 'view',
    inputs: [{ name: 'merchant', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getPurchase',
    stateMutability: 'view',
    inputs: [
      { name: 'merchant', type: 'address' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: [
      { name: 'userId', type: 'bytes32' },
      { name: 'item', type: 'string' },
      { name: 'quantity', type: 'bytes32' },
      { name: 'amount', type: 'bytes32' },
      { name: 'timestamp', type: 'uint64' },
    ],
  },
] as const;
